spring.application.name=backup-backend
logging.level.org.springframework.web=DEBUG

spring.datasource.url=jdbc:postgresql://2=10.202.150.153:5432/backup-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
